# Generated by Django 3.2.3 on 2021-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='max_visits',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
