# Generated by Django 3.2.3 on 2021-10-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_auto_20211021_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='max_visits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor'),
        ),
    ]
