# Generated by Django 3.2.3 on 2021-10-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_alter_visitor_visits_count'),
    ]

    operations = [

        migrations.AlterField(
            model_name='visitor',
            name='visits_count',
            field=models.IntegerField(default=0),
        ),

    ]
