# Generated by Django 3.2.3 on 2021-10-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_auto_20211021_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='max_visits',
        ),
    ]
