# Generated by Django 3.2.3 on 2021-10-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_remove_visitorlog_max_visits'),
    ]

    operations = [
    ]
